// ============================================================
// DATA-EXTRA.JS — Oxford 3000 Expansion (Batch 1 – 30 words)
// Load AFTER data.js. Merges into VOCABULARY array.
// ============================================================

const VOCAB_EXTRA_1 = [
  // EDUCATION
  {id:81,word:"achievement",pos:"noun",ipa:"/əˈtʃiːvmənt/",level:"B1",topic:"education",meaning_vn:"thành tích, thành tựu",meaning_en:"something difficult that you succeed in doing after much effort",collocations:["academic achievement","sense of achievement","outstanding achievement","achievement gap"],examples:["Her academic achievements earned her a full scholarship to university.","The school celebrated students' achievements at the annual awards ceremony."],synonyms:["accomplishment","attainment","success"]},
  {id:82,word:"analysis",pos:"noun",ipa:"/əˈnæləsɪs/",level:"B1",topic:"education",meaning_vn:"sự phân tích",meaning_en:"a careful study of something to understand it better",collocations:["critical analysis","data analysis","in-depth analysis","carry out analysis"],examples:["Students are required to write a critical analysis of the text.","A careful analysis of exam results showed significant improvements."],synonyms:["examination","evaluation","study"]},
  {id:83,word:"attitude",pos:"noun",ipa:"/ˈætɪtjuːd/",level:"B1",topic:"education",meaning_vn:"thái độ, quan điểm",meaning_en:"the way you think and feel about something",collocations:["positive attitude","attitude toward learning","change attitude","attitude problem"],examples:["A positive attitude toward studying is essential for academic success.","Teachers can greatly influence students' attitudes toward education."],synonyms:["outlook","mindset","approach"]},
  {id:84,word:"concentrate",pos:"verb",ipa:"/ˈkɒnsntreɪt/",level:"B1",topic:"education",meaning_vn:"tập trung",meaning_en:"to give all your attention to something",collocations:["concentrate on","hard to concentrate","concentrate efforts","fully concentrate"],examples:["It is difficult to concentrate on studying when there are many distractions.","Students need a quiet environment to concentrate effectively."],synonyms:["focus","pay attention","direct attention"]},
  {id:85,word:"discipline",pos:"noun",ipa:"/ˈdɪsəplɪn/",level:"B2",topic:"education",meaning_vn:"kỷ luật, sự rèn luyện bản thân",meaning_en:"the practice of training yourself to obey rules and control your behaviour",collocations:["self-discipline","school discipline","lack of discipline","maintain discipline"],examples:["Self-discipline is one of the most important qualities for academic success.","Good classroom discipline creates a better environment for learning."],synonyms:["self-control","order","training"]},
  {id:86,word:"effort",pos:"noun",ipa:"/ˈefət/",level:"B1",topic:"education",meaning_vn:"nỗ lực, cố gắng",meaning_en:"the physical or mental energy needed to do something",collocations:["make an effort","great effort","put in effort","combined effort"],examples:["Students who put in extra effort usually achieve better results in exams.","Learning a language requires consistent effort over a long period of time."],synonyms:["exertion","work","attempt"]},
  {id:87,word:"intelligence",pos:"noun",ipa:"/ɪnˈtelɪdʒəns/",level:"B1",topic:"education",meaning_vn:"trí thông minh, trí tuệ",meaning_en:"the ability to learn, understand, and think in a logical way",collocations:["artificial intelligence","emotional intelligence","high intelligence","intelligence test"],examples:["Emotional intelligence is just as important as academic ability in life.","Artificial intelligence is transforming education through personalized learning."],synonyms:["intellect","wisdom","reasoning"]},
  {id:88,word:"knowledge",pos:"noun",ipa:"/ˈnɒlɪdʒ/",level:"A2",topic:"education",meaning_vn:"kiến thức, hiểu biết",meaning_en:"the information and understanding that you have gained through learning",collocations:["general knowledge","background knowledge","expand knowledge","knowledge base"],examples:["Reading widely helps students expand their general knowledge.","A strong knowledge of grammar is essential for writing well in English."],synonyms:["understanding","expertise","information"]},
  {id:89,word:"participate",pos:"verb",ipa:"/pɑːˈtɪsɪpeɪt/",level:"B1",topic:"education",meaning_vn:"tham gia, tham dự",meaning_en:"to take part in an activity or event",collocations:["participate in","actively participate","participate in class","fully participate"],examples:["Students who actively participate in class tend to learn more effectively.","All citizens should participate in the democratic process of their country."],synonyms:["take part","engage","join in"]},
  {id:90,word:"succeed",pos:"verb",ipa:"/səkˈsiːd/",level:"A2",topic:"education",meaning_vn:"thành công, đạt được",meaning_en:"to achieve something that you have been trying to do",collocations:["succeed in","work hard to succeed","succeed academically","eventually succeed"],examples:["With determination and hard work, anyone can succeed in their studies.","She succeeded in passing the national exam with an excellent score."],synonyms:["achieve","accomplish","triumph"]},

  // ENVIRONMENT
  {id:91,word:"atmosphere",pos:"noun",ipa:"/ˈætməsfɪə(r)/",level:"B1",topic:"environment",meaning_vn:"khí quyển; bầu không khí",meaning_en:"the mixture of gases that surrounds the Earth",collocations:["Earth's atmosphere","pollute the atmosphere","atmosphere warms","damage the atmosphere"],examples:["Carbon dioxide emissions are rapidly warming Earth's atmosphere.","Deforestation reduces the number of trees that help clean our atmosphere."],synonyms:["air","climate","sky"]},
  {id:92,word:"collapse",pos:"verb",ipa:"/kəˈlæps/",level:"B2",topic:"environment",meaning_vn:"sụp đổ, sụp xuống",meaning_en:"to fall down suddenly; to suddenly fail or stop working",collocations:["ecosystem collapse","population collapse","risk of collapse","economic collapse"],examples:["Without protection, entire ecosystems could collapse within decades.","Fish populations have collapsed in many regions due to overfishing."],synonyms:["fail","break down","crumble"]},
  {id:93,word:"consume",pos:"verb",ipa:"/kənˈsjuːm/",level:"B1",topic:"environment",meaning_vn:"tiêu thụ, sử dụng",meaning_en:"to use energy, resources, food, or time",collocations:["consume energy","consume resources","consume less","consume fuel"],examples:["Developed countries consume far more natural resources than developing nations.","Electric vehicles consume less energy and produce fewer harmful emissions."],synonyms:["use","expend","burn through"]},
  {id:94,word:"crisis",pos:"noun",ipa:"/ˈkraɪsɪs/",level:"B2",topic:"environment",meaning_vn:"cuộc khủng hoảng",meaning_en:"a time of great danger or difficulty requiring immediate action",collocations:["climate crisis","environmental crisis","ecological crisis","face a crisis"],examples:["The world is facing a climate crisis that requires urgent international action.","The loss of biodiversity represents one of the most serious ecological crises of our time."],synonyms:["emergency","catastrophe","disaster"]},
  {id:95,word:"damage",pos:"noun",ipa:"/ˈdæmɪdʒ/",level:"B1",topic:"environment",meaning_vn:"thiệt hại, sự tổn hại",meaning_en:"physical harm that makes something worse or stops it from working",collocations:["environmental damage","cause damage","irreversible damage","damage to ecosystems"],examples:["Human activities have caused serious damage to the natural environment.","The oil spill caused irreversible damage to the marine ecosystem."],synonyms:["harm","destruction","injury"]},
  {id:96,word:"flood",pos:"noun",ipa:"/flʌd/",level:"B1",topic:"environment",meaning_vn:"lũ lụt",meaning_en:"a large amount of water covering an area that is usually dry",collocations:["flash flood","flood damage","flood risk","severe flooding"],examples:["Severe flooding caused by heavy rainfall displaced thousands of families.","Climate change is increasing the frequency and severity of floods worldwide."],synonyms:["inundation","deluge","overflow"]},
  {id:97,word:"protect",pos:"verb",ipa:"/prəˈtekt/",level:"A2",topic:"environment",meaning_vn:"bảo vệ",meaning_en:"to keep someone or something safe from harm, damage, or danger",collocations:["protect the environment","protect wildlife","protect species","strongly protect"],examples:["Governments must act urgently to protect endangered species from extinction.","Creating national parks helps protect natural habitats from human development."],synonyms:["defend","preserve","guard"]},
  {id:98,word:"species",pos:"noun",ipa:"/ˈspiːʃiːz/",level:"B2",topic:"environment",meaning_vn:"loài (sinh vật)",meaning_en:"a group of plants or animals whose members are similar and can breed together",collocations:["endangered species","native species","protect species","species extinction"],examples:["Many endangered species are at risk of extinction due to habitat destruction.","Scientists have discovered thousands of new species in the Amazon rainforest."],synonyms:["type","kind","variety"]},
  {id:99,word:"waste",pos:"noun",ipa:"/weɪst/",level:"B1",topic:"environment",meaning_vn:"chất thải; sự lãng phí",meaning_en:"material that has been used and is no longer needed; careless use of resources",collocations:["reduce waste","plastic waste","industrial waste","waste management"],examples:["Reducing plastic waste is one of the most pressing environmental challenges today.","Industrial waste is contaminating rivers and threatening aquatic ecosystems."],synonyms:["garbage","rubbish","trash"]},
  {id:100,word:"wildlife",pos:"noun",ipa:"/ˈwaɪldlaɪf/",level:"B2",topic:"environment",meaning_vn:"động vật hoang dã",meaning_en:"animals, birds, and plants living in their natural environment",collocations:["protect wildlife","wildlife conservation","wildlife habitat","threaten wildlife"],examples:["National parks play a vital role in protecting wildlife and their habitats.","Urban expansion is destroying the natural habitats that wildlife depends on."],synonyms:["fauna","animals","nature"]},

  // TECHNOLOGY
  {id:101,word:"accurate",pos:"adjective",ipa:"/ˈækjərət/",level:"B2",topic:"technology",meaning_vn:"chính xác, đúng đắn",meaning_en:"correct and true in every detail",collocations:["highly accurate","accurate data","accurate information","accurate result"],examples:["Modern GPS systems are highly accurate, locating you within a few meters.","It is important to use accurate and reliable sources when doing research online."],synonyms:["precise","correct","exact"]},
  {id:102,word:"application",pos:"noun",ipa:"/ˌæplɪˈkeɪʃn/",level:"B1",topic:"technology",meaning_vn:"ứng dụng, phần mềm",meaning_en:"a program designed for a particular purpose on a computer or mobile phone",collocations:["mobile application","software application","download an application","educational app"],examples:["Educational applications have made it much easier for students to learn languages.","Many businesses now develop their own mobile applications to serve customers better."],synonyms:["app","software","program"]},
  {id:103,word:"device",pos:"noun",ipa:"/dɪˈvaɪs/",level:"A2",topic:"technology",meaning_vn:"thiết bị, dụng cụ",meaning_en:"a machine or tool that has been made for a particular purpose",collocations:["electronic device","mobile device","smart device","use a device"],examples:["Smartphones are the most widely used electronic devices in the world today.","Smart home devices are transforming the way we manage our daily lives."],synonyms:["machine","gadget","tool"]},
  {id:104,word:"network",pos:"noun",ipa:"/ˈnetwɜːk/",level:"A2",topic:"technology",meaning_vn:"mạng lưới, mạng máy tính",meaning_en:"a system of connected things, people, or organizations",collocations:["social network","computer network","network security","build a network"],examples:["Social networks have completely changed the way people communicate and share information.","A fast and reliable computer network is essential for every modern business."],synonyms:["system","web","grid"]},
  {id:105,word:"software",pos:"noun",ipa:"/ˈsɒftweə(r)/",level:"B1",topic:"technology",meaning_vn:"phần mềm máy tính",meaning_en:"the programs used by a computer to do specific tasks",collocations:["software development","install software","software update","design software"],examples:["New educational software is helping students learn more effectively at home.","The company invested heavily in developing advanced data analysis software."],synonyms:["program","application","system"]},

  // HEALTH
  {id:106,word:"disease",pos:"noun",ipa:"/dɪˈziːz/",level:"A2",topic:"health",meaning_vn:"bệnh tật, bệnh dịch",meaning_en:"an illness of people, animals, or plants caused by infection or a medical condition",collocations:["infectious disease","chronic disease","prevent disease","spread of disease"],examples:["Vaccination is one of the most effective ways to prevent infectious disease.","Chronic diseases like diabetes require careful and long-term management."],synonyms:["illness","sickness","condition"]},
  {id:107,word:"mental",pos:"adjective",ipa:"/ˈmentl/",level:"B1",topic:"health",meaning_vn:"thuộc về tinh thần, tâm lý",meaning_en:"connected with or happening in the mind",collocations:["mental health","mental illness","mental wellbeing","mental strength"],examples:["Mental health is just as important as physical health for overall wellbeing.","Schools are now placing much greater emphasis on students' mental wellbeing."],synonyms:["psychological","emotional","cognitive"]},
  {id:108,word:"recover",pos:"verb",ipa:"/rɪˈkʌvə(r)/",level:"B2",topic:"health",meaning_vn:"hồi phục, bình phục",meaning_en:"to return to a normal state of health, mind, or strength after illness or difficulty",collocations:["recover from illness","fully recover","recovery process","recover quickly"],examples:["It took several weeks for him to fully recover from the surgery.","Regular exercise can help patients recover more quickly from many illnesses."],synonyms:["heal","get better","recuperate"]},
  {id:109,word:"stress",pos:"noun",ipa:"/stres/",level:"A2",topic:"health",meaning_vn:"căng thẳng, áp lực",meaning_en:"a state of worry or tension caused by difficult situations",collocations:["exam stress","manage stress","stress level","reduce stress"],examples:["Exam stress is a very common problem among high school students in Vietnam.","Regular exercise and meditation are effective ways to manage daily stress."],synonyms:["anxiety","pressure","tension"]},

  // CULTURE
  {id:110,word:"community",pos:"noun",ipa:"/kəˈmjuːnəti/",level:"A2",topic:"culture",meaning_vn:"cộng đồng",meaning_en:"a group of people living in the same area or sharing common interests",collocations:["local community","build community","community spirit","serve the community"],examples:["A strong community spirit helps residents support each other through difficult times.","Local communities play a vital role in preserving and passing on traditional culture."],synonyms:["society","group","neighborhood"]},
];

// Merge into the main VOCABULARY array
if (typeof VOCABULARY !== 'undefined') {
  VOCABULARY.push(...VOCAB_EXTRA_1);
}
